import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { access, stat, copyFile, readdir, rm, mkdir } from "fs/promises";
import path from "path";
const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const ios = (process.argv[2] === "ios");

async function pathExists(p) {
    try {
        await access(p);
        return true;
    } catch {
        return false;
    }
}

async function emptyDir(dir) {
    try {
        const entries = await readdir(dir);
        await Promise.all(
            entries.map((entry) => rm(path.join(dir, entry), { recursive: true, force: true }))
        );
    } catch {
        await mkdir(dir, { recursive: true });
    }
}

async function copyFiles() {
    const filesToCopy = ["manifest.json", "styles.css"];

    for (const file of filesToCopy) {
        const srcPath = path.join(process.cwd(), file);
        const destPath = path.join(process.cwd(), "dist", file);

        // Check if the file exists
        if (await pathExists(srcPath)) {
            // Check if the destination file exists and if it has changed
            if (await pathExists(destPath)) {
                const srcStats = await stat(srcPath);
                const destStats = await stat(destPath);

                // Copy only if the source file has been modified after the destination file
                if (srcStats.mtime > destStats.mtime) {
                    await copyFile(srcPath, destPath);
                    console.log(`Copied ${file} to dist/`);
                } else {
                    console.log(`${file} is unchanged, not copying.`);
                }
            } else {
                // If the destination file does not exist, copy it
                await copyFile(srcPath, destPath);
                console.log(`Copied ${file} to dist/`);
            }
        } else {
            console.warn(`${file} does not exist, skipping.`);
        }
    }
}


async function build() {
    await emptyDir("dist");

    const context = await esbuild.context({
        banner: {
            js: banner,
        },
        entryPoints: ["src/main.ts"],
        bundle: true,
        external: [
            "obsidian",
            "electron",
            "@codemirror/autocomplete",
            "@codemirror/collab",
            "@codemirror/commands",
            "@codemirror/language",
            "@codemirror/lint",
            "@codemirror/search",
            "@codemirror/state",
            "@codemirror/view",
            "@lezer/common",
            "@lezer/highlight",
            "@lezer/lr",
            ...builtinModules],
        format: "cjs",
        target: "es2018",
        logLevel: "info",
        sourcemap: prod ? false : "inline",
        treeShaking: true,
        outfile: "dist/main.js",
        drop: prod ? ["debugger"] : [], // Remove debugger statements in production
        keepNames: true, // Preserve function/class names for better debugging
    });

    if (prod || ios) {
        await context.rebuild();
        await copyFiles();
        context.dispose();
    } else {
        await context.rebuild();
        await copyFiles();
        await context.watch();
    }

    console.log("Build complete");
}

build().catch((err) => {
    console.error(err);
    process.exit(1);
});
