conversation_schema:
    required_fields:
        conversation_id: "conversation_id"
        conversation_model: "Unspecified"
        create_time:
            field: "create_time"
            format: "unix"
        update_time:
            field: "update_time"
            format: "unix"
        chat_messages: "mapping"
    message_schema:
        message_id: "id"
        role: "author.role"
        message_content: "content.parts"
        created_at:
            field: "create_time"
            format: "unix"
        updated_at:
            field: "update_time"
            format: "unix"
        message_model: "model_slug"
