/**
 * Types for Google Gemini (Takeout My Activity) exports
 */

/**
 * A single activity entry from Google Takeout My Activity JSON for Gemini Apps
 */
export interface GeminiActivityEntry {
	/**
	 * Header text (e.g., "Gemini Apps")
	 */
	header: string;

	/**
	 * Title of the activity (often the user's prompt/question)
	 */
	title: string;

	/**
	 * ISO 8601 timestamp string
	 */
	time: string;

	/**
	 * HTML content items (typically the assistant's response)
	 */
	safeHtmlItem?: Array<{
		html: string;
	}>;

	/**
	 * Subtitles (additional metadata)
	 */
	subtitles?: Array<{
		name: string;
		url?: string;
	}>;

	/**
	 * List of attached file names (images, documents, etc.)
	 */
	attachedFiles?: string[];

	/**
	 * User-uploaded image file name (if any)
	 */
	imageFile?: string;

	/**
	 * Google products associated with this activity
	 */
	products?: string[];

	/**
	 * Activity controls metadata
	 */
	activityControls?: string[];

	/**
	 * Location information (if available)
	 */
	locationInfos?: any[];

	/**
	 * Details array (additional structured data)
	 */
	details?: Array<{
		name: string;
	}>;
}

/**
 * Gemini Index - Generated by browser extension from live Gemini web app
 * Contains conversation IDs and metadata not available in Takeout exports
 */
export interface GeminiIndex {
	/**
	 * When the index was extracted
	 */
	extractedAt: string;

	/**
	 * Total number of conversations found
	 */
	totalConversations: number;

	/**
	 * Number of successfully extracted conversations
	 */
	successfulExtractions: number;

	/**
	 * Total unique messages across all conversations
	 */
	uniqueMessages: number;

	/**
	 * Source method used for extraction (e.g., "dom-click-with-change-detection")
	 */
	source: string;

	/**
	 * Array of conversation metadata
	 */
	conversations: IndexConversation[];
}

/**
 * Single conversation entry in the Gemini index
 */
export interface IndexConversation {
	/**
	 * Unique conversation ID from Gemini (e.g., "c_785f8f69017f7c11")
	 */
	conversationId: string;

	/**
	 * Conversation title
	 */
	title: string;

	/**
	 * Full URL to the conversation in Gemini web app
	 */
	url: string;

	/**
	 * First message metadata (used for matching with Takeout entries)
	 */
	firstMessage: IndexMessage;

	/**
	 * Whether the conversation was successfully loaded during extraction
	 */
	loadSuccess: boolean;
}

/**
 * Message metadata in the index (lightweight, for matching purposes)
 */
export interface IndexMessage {
	/**
	 * Message ID from Gemini
	 */
	messageId: string;

	/**
	 * Preview of message content (first ~20 characters)
	 */
	preview: string;

	/**
	 * Full length of the message content
	 */
	length: number;
}

