/**
 * Types for Google Gemini (Takeout My Activity) exports
 */

/**
 * A single activity entry from Google Takeout My Activity JSON for Gemini Apps
 */
export interface GeminiActivityEntry {
	/**
	 * Header text (e.g., "Gemini Apps")
	 */
	header: string;

	/**
	 * Title of the activity (often the user's prompt/question)
	 */
	title: string;

	/**
	 * ISO 8601 timestamp string
	 */
	time: string;

	/**
	 * HTML content items (typically the assistant's response)
	 */
	safeHtmlItem?: Array<{
		html: string;
	}>;

	/**
	 * Subtitles (additional metadata)
	 */
	subtitles?: Array<{
		name: string;
		url?: string;
	}>;

	/**
	 * List of attached file names (images, documents, etc.)
	 */
	attachedFiles?: string[];

	/**
	 * User-uploaded image file name (if any)
	 */
	imageFile?: string;

	/**
	 * Google products associated with this activity
	 */
	products?: string[];

	/**
	 * Activity controls metadata
	 */
	activityControls?: string[];

	/**
	 * Location information (if available)
	 */
	locationInfos?: any[];

	/**
	 * Details array (additional structured data)
	 */
	details?: Array<{
		name: string;
	}>;
}

/**
 * Gemini Index - Generated by browser extension from live Gemini web app
 * Contains conversation IDs and metadata not available in Takeout exports
 */
export interface GeminiIndex {
	/**
	 * When the index was extracted
	 */
	extractedAt: string;

	/**
	 * Total number of conversations found
	 */
	totalConversations: number;

	/**
	 * Number of successfully extracted conversations
	 */
	successfulExtractions: number;

	/**
	 * Total unique messages across all conversations
	 */
	uniqueMessages: number;

	/**
	 * Source method used for extraction (e.g., "dom-click-with-change-detection")
	 */
	source: string;

	/**
	 * Array of conversation metadata
	 */
	conversations: IndexConversation[];
}

/**
 * Single conversation entry in the Gemini index
 */
export interface IndexConversation {
    /**
     * Unique conversation ID from Gemini (e.g., "c_785f8f69017f7c11")
     */
    conversationId: string;

    /**
     * Conversation title
     */
    title: string;

    /**
     * Full URL to the conversation in Gemini web app
     */
    url: string;

    /**
     * First message metadata (used for matching with Takeout entries)
     */
    firstMessage: IndexMessage;

    /**
     * Optional detailed messages with hashes, when provided by the extension.
     * This allows robust matching with Takeout entries using messageHash.
     */
    messages?: IndexHashedMessage[];

    /**
     * Whether the conversation was successfully loaded during extraction
     */
    loadSuccess: boolean;
}

/**
 * Message metadata for the first message (legacy/lightweight, no hash)
 */
export interface IndexMessage {
    /**
     * Message ID from Gemini
     */
    messageId: string;

    /**
     * Preview of message content (first ~20 characters)
     */
    preview: string;

    /**
     * Full length of the message content
     */
    length: number;
}

/**
 * Detailed message metadata with hash, used for matching Takeout entries.
 */
export interface IndexHashedMessage {
    /**
     * Message ID from Gemini DOM
     */
    messageId: string;

    /**
     * SHA-256 hash of the full user prompt content (after normalization)
     */
    messageHash: string;

    /**
     * Full length of the message content
     */
    length: number;

    /**
     * Optional timestamp string (reserved for future use if we can
     * reliably extract it from the live Gemini UI).
     */
    timestamp?: string;
}

