/**
 * Nexus AI Chat Importer - Obsidian Plugin
 * Copyright (C) 2024 Akim Sissaoui
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// src/models/import-report.ts
import { AttachmentStats, MessageTimestampFormat } from "../types/plugin";
import { formatMessageTimestamp } from "../utils";
import type {
    AnalysisInfo,
    FileAnalysisStats,
} from "../services/conversation-metadata-extractor";

interface ReportEntry {
    title: string;
    filePath: string;
    createTime: number; // Unix timestamp (seconds)
    updateTime: number; // Unix timestamp (seconds)
    messageCount?: number;
    newMessageCount?: number; // For updates
    providerSpecificCount?: number; // For provider-specific column (artifacts, attachments, etc.)
    reason?: string;
    errorMessage?: string;
    attachmentStats?: AttachmentStats;
    sourceFile?: string; // Track which ZIP file this entry came from
}

interface ProcessingCounters {
    totalConversationsProcessed: number;
    totalNewConversationsSuccessfullyImported: number;
    totalConversationsActuallyUpdated: number;
    totalNonEmptyMessagesAdded: number;
}

interface FileSection {
    fileName: string;
    created: ReportEntry[];
    updated: ReportEntry[];
    recreated: ReportEntry[];
    skipped: ReportEntry[];
    failed: ReportEntry[];
    ignored: ReportEntry[];
    counters: ProcessingCounters;
}

/**
 * Every conversation number the plugin reports, resolved from the two phases
 * that produce them. See `ImportReport.getConversationLedger`.
 */
export interface ConversationLedger {
    /** False on the mobile flow, which never runs an archive analysis. */
    analysisAvailable: boolean;

    /** Raw conversation entries across every archive, duplicates included. */
    totalFound: number;
    /** Distinct conversation ids kept after collapsing duplicates. */
    uniqueKept: number;
    /** Already up to date in the vault — a state, rebuild or not. */
    unchanged: number;
    /** The subset of `unchanged` pulled back in by a rebuild request. */
    reprocessed: number;

    /** Notes written for the first time. */
    created: number;
    /** Existing notes that gained the messages they lacked. */
    updated: number;
    /** Existing notes regenerated from scratch on a rebuild request. */
    recreated: number;
    /** Conversations that errored during processing. */
    failed: number;
    /** Conversations with no exportable content. */
    empty: number;
    /** Notes regenerated byte-identical — nothing was written. */
    noChange: number;

    /**
     * Conversations this run was asked to import. It is what every outcome
     * below adds up to, which is why the reports carry it rather than the
     * declined remainder: on a full import nothing is declined, and the
     * number is still the kept population.
     */
    selected: number;
    /**
     * Conversations offered in the selection dialog that the user left
     * unchecked. `null` when no selection step ran (a full import).
     */
    notSelected: number | null;
    /** Not imported because the vault copy was already current. */
    unchangedSkipped: number;
    /** Conversations this run was about. */
    totalConversations: number;
    /** Duplicate ids collapsed across archives. */
    duplicates: number;
}

/** What happened to a note, for the index listings. */
type NoteOutcome = "created" | "updated" | "recreated";

/** Which outcome wins when one note is written twice in a single run. */
const OUTCOME_RANK: Record<NoteOutcome, number> = {
    created: 0,
    updated: 1,
    recreated: 2,
};

interface ReportCrossLinks {
    summaryFileName: string;
    heavyFileName: string;
    mobileFileName: string;
}

interface IgnoredArchiveDetail {
    fileName: string;
    reason: string;
    message: string;
}

export class ImportReport {
    private fileSections: Map<string, FileSection> = new Map();
    private currentFileName: string = "";
    private globalErrors: { message: string; details: string }[] = [];
    private providerSpecificColumnHeader: string = "Attachments";
    private operationStartTime: number = Date.now();
    private fileStats?: Map<string, FileAnalysisStats>;
    private analysisInfo?: AnalysisInfo;
    private customTimestampFormat?: MessageTimestampFormat; // Custom format for report dates
    private ignoredArchiveDetails: Map<string, IgnoredArchiveDetail> =
        new Map();
    private selection?: { offered: number; selected: number };

    /**
     * Start a new file section for multi-file imports
     */
    startFileSection(fileName: string) {
        this.currentFileName = fileName;
        if (!this.fileSections.has(fileName)) {
            this.fileSections.set(fileName, {
                fileName,
                created: [],
                updated: [],
                recreated: [],
                skipped: [],
                failed: [],
                ignored: [],
                counters: {
                    totalConversationsProcessed: 0,
                    totalNewConversationsSuccessfullyImported: 0,
                    totalConversationsActuallyUpdated: 0,
                    totalNonEmptyMessagesAdded: 0,
                },
            });
        }
    }

    /**
     * Set counters for the current file section
     */
    setFileCounters(counters: ProcessingCounters) {
        const section = this.getCurrentSection();
        if (section) {
            section.counters = counters;
        }
    }

    private getCurrentSection(): FileSection | undefined {
        return this.fileSections.get(this.currentFileName);
    }

    setProviderSpecificColumnHeader(header: string) {
        this.providerSpecificColumnHeader = header;
    }

    setCustomTimestampFormat(format?: MessageTimestampFormat) {
        this.customTimestampFormat = format;
    }

    /**
     * Legacy method for backward compatibility (single file imports)
     */
    private getTotalAttachmentStats(): AttachmentStats {
        const total = {
            total: 0,
            found: 0,
            inline: 0,
            notProvided: 0,
            missing: 0,
            failed: 0,
        };

        this.fileSections.forEach((section) => {
            [
                ...section.created,
                ...section.updated,
                ...section.recreated,
            ].forEach((entry) => {
                if (entry.attachmentStats) {
                    total.total += entry.attachmentStats.total;
                    total.found += entry.attachmentStats.found;
                    total.inline += entry.attachmentStats.inline;
                    total.notProvided += entry.attachmentStats.notProvided;
                    total.missing += entry.attachmentStats.missing;
                    total.failed += entry.attachmentStats.failed;
                }

                // Artifacts are always successfully created — count as found
                if (entry.providerSpecificCount) {
                    total.total += entry.providerSpecificCount;
                    total.found += entry.providerSpecificCount;
                }
            });
        });

        return total;
    }

    private getFileSectionAttachmentStats(
        section: FileSection
    ): AttachmentStats {
        const total = {
            total: 0,
            found: 0,
            inline: 0,
            notProvided: 0,
            missing: 0,
            failed: 0,
        };

        [...section.created, ...section.updated, ...section.recreated].forEach(
            (entry) => {
                if (entry.attachmentStats) {
                    total.total += entry.attachmentStats.total;
                    total.found += entry.attachmentStats.found;
                    total.inline += entry.attachmentStats.inline;
                    total.notProvided += entry.attachmentStats.notProvided;
                    total.missing += entry.attachmentStats.missing;
                    total.failed += entry.attachmentStats.failed;
                }

                if (entry.providerSpecificCount) {
                    total.total += entry.providerSpecificCount;
                    total.found += entry.providerSpecificCount;
                }
            }
        );

        return total;
    }

    private generateAttachmentSummary(stats: AttachmentStats): string {
        if (stats.total === 0) return "";

        let s = `### 📎 Attachment Summary\n\n`;
        s += `| Status | Count |\n`;
        s += `|:---|---:|\n`;
        s += `| **Total** | **${stats.total}** |\n`;
        if (stats.found > 0)
            s += `| ✅ Extracted to vault | ${stats.found} |\n`;
        if (stats.inline > 0)
            s += `| 📄 Inline (embedded) | ${stats.inline} |\n`;
        if (stats.notProvided > 0)
            s += `| ℹ️ Not provided by export | ${stats.notProvided} |\n`;
        if (stats.missing > 0)
            s += `| ⚠️ Missing from export | ${stats.missing} |\n`;
        if (stats.failed > 0) s += `| ❌ Failed | ${stats.failed} |\n`;
        return s + `\n`;
    }

    private getGlobalStats() {
        let created = 0;
        let updated = 0;
        let recreated = 0;
        let skipped = 0;
        let failed = 0;
        let totalProcessed = 0;
        let newMessages = 0;

        this.fileSections.forEach((section) => {
            created += section.created.length;
            updated += section.updated.length;
            recreated += section.recreated.length;
            skipped += section.skipped.length;
            failed += section.failed.length;
            totalProcessed += section.counters.totalConversationsProcessed;
            newMessages += section.counters.totalNonEmptyMessagesAdded;
        });

        return {
            created,
            updated,
            recreated,
            skipped,
            failed,
            totalProcessed,
            newMessages,
        };
    }

    addCreated(
        title: string,
        filePath: string,
        createTime: number,
        updateTime: number,
        messageCount: number,
        attachmentStats?: AttachmentStats,
        providerSpecificCount?: number
    ) {
        const section = this.getCurrentSection();
        if (section) {
            section.created.push({
                title,
                filePath,
                createTime,
                updateTime,
                messageCount,
                attachmentStats,
                providerSpecificCount,
                sourceFile: this.currentFileName,
            });
        }
    }

    addUpdated(
        title: string,
        filePath: string,
        createTime: number,
        updateTime: number,
        newMessageCount: number,
        attachmentStats?: AttachmentStats,
        providerSpecificCount?: number
    ) {
        const section = this.getCurrentSection();
        if (section) {
            section.updated.push({
                title,
                filePath,
                createTime,
                updateTime,
                newMessageCount,
                attachmentStats,
                providerSpecificCount,
                sourceFile: this.currentFileName,
            });
        }
    }

    /**
     * An existing note regenerated from scratch. Distinct from addUpdated,
     * which appends what a note lacks: nothing of the previous file survives
     * a rebuild, so reporting the two as one outcome would hide it.
     */
    addRecreated(
        title: string,
        filePath: string,
        createTime: number,
        updateTime: number,
        messageCount: number,
        attachmentStats?: AttachmentStats,
        providerSpecificCount?: number
    ) {
        const section = this.getCurrentSection();
        if (section) {
            section.recreated.push({
                title,
                filePath,
                createTime,
                updateTime,
                messageCount,
                attachmentStats,
                providerSpecificCount,
                sourceFile: this.currentFileName,
            });
        }
    }

    addSkipped(
        title: string,
        filePath: string,
        createTime: number,
        updateTime: number,
        messageCount: number,
        reason: string,
        attachmentStats?: AttachmentStats,
        providerSpecificCount?: number
    ) {
        const section = this.getCurrentSection();
        if (section) {
            section.skipped.push({
                title,
                filePath,
                createTime,
                updateTime,
                messageCount,
                reason,
                attachmentStats,
                providerSpecificCount,
                sourceFile: this.currentFileName,
            });
        }
    }

    addIgnored(
        title: string,
        filePath: string,
        createTime: number,
        updateTime: number
    ) {
        const section = this.getCurrentSection();
        if (section) {
            section.ignored.push({
                title,
                filePath,
                createTime,
                updateTime,
                sourceFile: this.currentFileName,
            });
        }
    }

    addFailed(
        title: string,
        filePath: string,
        createTime: number,
        updateTime: number,
        errorMessage: string
    ) {
        const section = this.getCurrentSection();
        if (section) {
            section.failed.push({
                title,
                filePath,
                createTime,
                updateTime,
                errorMessage,
                sourceFile: this.currentFileName,
            });
        }
    }

    addError(message: string, details: string) {
        this.globalErrors.push({ message, details });
    }

    /**
     * The analysis and per-file stats come from `setAnalysisInfo` /
     * `setFileStats` rather than parameters: the caller already handed them
     * over, and passing them twice let the two copies drift apart.
     */
    generateSummaryReportContent(
        allFiles?: File[],
        processedFiles?: string[],
        skippedFiles?: string[],
        isSelectiveImport?: boolean,
        archiveDisplayNames?: Map<string, string>,
        links?: ReportCrossLinks,
        archiveTimestamps?: Map<string, string>
    ): string {
        const ledger = this.getConversationLedger();
        const totalAttachments = this.getTotalAttachmentStats();
        const totalFilesAnalyzed = allFiles
            ? allFiles.length
            : this.fileSections.size;
        const processedSet = new Set(processedFiles || []);
        const skippedSet = new Set(skippedFiles || []);

        const lines: string[] = [];
        lines.push("# Nexus AI Chat Importer Summary");
        lines.push("");

        if (links) {
            lines.push(`- Heavy index: [[${links.heavyFileName}]]`);
            lines.push(`- Mobile index: [[${links.mobileFileName}]]`);
            lines.push("");
        }

        lines.push("## Overview");
        lines.push("");
        lines.push("### Files");
        lines.push("");
        lines.push("| Metric | Value |");
        lines.push("| --- | ---: |");
        lines.push(`| Analyzed | ${totalFilesAnalyzed} |`);
        lines.push(`| Processed | ${processedSet.size} |`);
        lines.push(`| Not processed | ${skippedSet.size} |`);
        lines.push("");

        // The Archives table below carries provenance when there are several
        // archives; with one, this line is the only place the name survives.
        if (allFiles && allFiles.length === 1) {
            const only = allFiles[0];
            const timestamp = archiveTimestamps?.get(only.name);
            lines.push(
                `Archive: \`${only.name}\`${timestamp ? ` — ${timestamp}` : ""}`
            );
            lines.push("");
        }

        // Two tables, two questions. The archive one ends on Selected, which
        // is what the outcome table below it adds up to — a reader can check
        // the arithmetic instead of taking nine flat rows on trust.
        if (ledger.analysisAvailable) {
            lines.push("### Archive");
            lines.push("");
            lines.push("| Metric | Value |");
            lines.push("| --- | ---: |");
            lines.push(`| Found | ${ledger.totalFound} |`);
            lines.push(`| Duplicates removed | ${ledger.duplicates} |`);
            lines.push(`| Kept | ${ledger.uniqueKept} |`);
            lines.push(`| Selected | ${ledger.selected} |`);
            lines.push("");
        }

        lines.push("### Notes");
        lines.push("");
        lines.push("| Outcome | Conversations |");
        lines.push("| --- | ---: |");
        lines.push(`| ✨ Created | ${ledger.created} |`);
        lines.push(`| 🔄 Updated | ${ledger.updated} |`);
        lines.push(`| ♻️ Recreated | ${ledger.recreated} |`);
        lines.push(`| ⏭️ Unchanged | ${ledger.unchangedSkipped} |`);
        if (ledger.empty > 0) {
            lines.push(`| 🚫 Empty (no content) | ${ledger.empty} |`);
        }
        lines.push(`| ❌ Failed | ${ledger.failed} |`);
        lines.push("");

        lines.push(this.generateAttachmentSummary(totalAttachments));

        // Twelve columns earn their place only when there is something to
        // compare. With a single archive every cell repeats the Overview.
        if (allFiles && allFiles.length > 1) {
            const sortedFiles = [...allFiles].sort(
                (a, b) => a.lastModified - b.lastModified
            );
            lines.push("## Archives");
            lines.push("");
            lines.push(
                "| Archive | Timestamp | Status | Reason | Conversations | Selected | Created | Updated | Recreated | Unchanged | Failed | Duplicates |"
            );
            lines.push(
                "| --- | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"
            );

            for (const file of sortedFiles) {
                const section = this.fileSections.get(file.name);
                const perFileStats = this.fileStats?.get(file.name);
                const shortName =
                    archiveDisplayNames?.get(file.name) || file.name;
                const timestamp = archiveTimestamps?.get(file.name) ?? "—";
                const selectedCount =
                    perFileStats?.selectedForImport ??
                    (section?.created.length || 0) +
                        (section?.updated.length || 0) +
                        (section?.recreated.length || 0);
                const createdCount = section?.created.length || 0;
                const updatedCount = section?.updated.length || 0;
                const recreatedCount = section?.recreated.length || 0;
                const failedCount = section?.failed.length || 0;
                const duplicateCount = perFileStats?.duplicates ?? 0;
                const unchangedCount =
                    perFileStats?.unchangedConversations ?? 0;
                const conversationCount =
                    perFileStats?.totalConversations ?? selectedCount;
                const status = processedSet.has(file.name)
                    ? "processed"
                    : "not processed";
                const reason = this.buildArchiveReason(
                    file.name,
                    status,
                    isSelectiveImport
                );

                lines.push(
                    `| \`${shortName}\` | ${timestamp} | ${status} | ${reason} | ${conversationCount} | ${selectedCount} | ${createdCount} | ${updatedCount} | ${recreatedCount} | ${unchangedCount} | ${failedCount} | ${duplicateCount} |`
                );
            }
            lines.push("");

            if (archiveDisplayNames && archiveDisplayNames.size > 0) {
                lines.push("## Archive Name Map");
                lines.push("");
                lines.push("| Short Name | Timestamp | Original File Name |");
                lines.push("| --- | --- | --- |");
                for (const file of sortedFiles) {
                    const shortName = archiveDisplayNames.get(file.name);
                    if (!shortName || shortName === file.name) {
                        continue;
                    }
                    const timestamp = archiveTimestamps?.get(file.name) ?? "—";
                    lines.push(
                        `| \`${shortName}\` | ${timestamp} | \`${file.name}\` |`
                    );
                }
                lines.push("");
            }
        }

        if (this.globalErrors.length > 0) {
            lines.push("## Global Errors");
            lines.push("");
            for (const entry of this.globalErrors) {
                lines.push(`- **${entry.message}**: ${entry.details}`);
            }
            lines.push("");
        } else if (isSelectiveImport) {
            lines.push("## Global Errors");
            lines.push("");
            lines.push("- None");
            lines.push("");
        }

        return lines.join("\n");
    }

    generateHeavyIndexContent(
        allFiles?: File[],
        links?: ReportCrossLinks
    ): string {
        const stats = this.getGlobalStats();
        const fileNames = this.getOrderedFileNames(allFiles);
        const lines: string[] = [];

        lines.push("# Nexus AI Chat Importer Index (Heavy)");
        lines.push("");
        if (links) {
            lines.push(`- Summary: [[${links.summaryFileName}]]`);
            lines.push(`- Mobile index: [[${links.mobileFileName}]]`);
            lines.push("");
        }
        lines.push("## Index Summary");
        lines.push("");
        lines.push(`- Created: ${stats.created}`);
        lines.push(`- Updated: ${stats.updated}`);
        lines.push(`- Recreated: ${stats.recreated}`);
        lines.push(`- Failed: ${stats.failed}`);
        lines.push(`- Files with entries: ${fileNames.length}`);
        lines.push("");

        if (fileNames.length === 0) {
            lines.push("No indexed conversations.");
            lines.push("");
            return lines.join("\n");
        }

        const multipleFiles = fileNames.length > 1;
        for (let index = 0; index < fileNames.length; index++) {
            const fileName = fileNames[index];
            const section = this.fileSections.get(fileName);
            if (!section) {
                continue;
            }

            if (multipleFiles) {
                lines.push(`## ${fileName}`);
                lines.push("");
            }

            const sectionContent = this.generateFileContent(
                section,
                multipleFiles
            ).trim();
            if (sectionContent.length > 0) {
                lines.push(sectionContent);
                lines.push("");
            }
        }

        return lines.join("\n");
    }

    generateMobileIndexContent(
        allFiles?: File[],
        links?: ReportCrossLinks
    ): string {
        const fileNames = this.getOrderedFileNames(allFiles);
        const createdOrUpdatedByPath = new Map<
            string,
            {
                title: string;
                filePath: string;
                updateTime: number;
                sourceFile?: string;
                status: NoteOutcome;
            }
        >();
        const failedEntries: ReportEntry[] = [];

        const upsertEntry = (entry: ReportEntry, status: NoteOutcome) => {
            const current = createdOrUpdatedByPath.get(entry.filePath);
            if (!current) {
                createdOrUpdatedByPath.set(entry.filePath, {
                    title: entry.title,
                    filePath: entry.filePath,
                    updateTime: entry.updateTime,
                    sourceFile: entry.sourceFile,
                    status,
                });
                return;
            }

            const shouldRefreshMetadata =
                entry.updateTime >= current.updateTime;
            createdOrUpdatedByPath.set(entry.filePath, {
                title: shouldRefreshMetadata ? entry.title : current.title,
                filePath: current.filePath,
                updateTime: shouldRefreshMetadata
                    ? entry.updateTime
                    : current.updateTime,
                sourceFile: shouldRefreshMetadata
                    ? entry.sourceFile
                    : current.sourceFile,
                // A note listed twice keeps the strongest thing that
                // happened to it: a rebuild outranks an append, which
                // outranks a first write.
                status:
                    OUTCOME_RANK[status] >= OUTCOME_RANK[current.status]
                        ? status
                        : current.status,
            });
        };

        for (const fileName of fileNames) {
            const section = this.fileSections.get(fileName);
            if (!section) {
                continue;
            }

            for (const entry of section.created) {
                upsertEntry(entry, "created");
            }
            for (const entry of section.updated) {
                upsertEntry(entry, "updated");
            }
            for (const entry of section.recreated) {
                upsertEntry(entry, "recreated");
            }

            failedEntries.push(...section.failed);
        }

        const indexedEntries = Array.from(createdOrUpdatedByPath.values());
        const createdEntries = indexedEntries
            .filter((entry) => entry.status === "created")
            .sort((a, b) =>
                a.title.localeCompare(b.title, undefined, {
                    sensitivity: "base",
                })
            );
        const updatedEntries = indexedEntries
            .filter((entry) => entry.status === "updated")
            .sort((a, b) =>
                a.title.localeCompare(b.title, undefined, {
                    sensitivity: "base",
                })
            );
        const recreatedEntries = indexedEntries
            .filter((entry) => entry.status === "recreated")
            .sort((a, b) =>
                a.title.localeCompare(b.title, undefined, {
                    sensitivity: "base",
                })
            );

        const sortedAllEntries = [...indexedEntries].sort((a, b) => {
            return a.title.localeCompare(b.title, undefined, {
                sensitivity: "base",
            });
        });

        const lines: string[] = [];
        lines.push("# Nexus AI Chat Importer Index (Mobile)");
        lines.push("");
        if (links) {
            lines.push(`- Summary: [[${links.summaryFileName}]]`);
            lines.push(`- Heavy index: [[${links.heavyFileName}]]`);
            lines.push("");
        }
        lines.push("## Index Summary");
        lines.push("");
        lines.push(`- Conversations listed: ${sortedAllEntries.length}`);
        lines.push(`- New notes: ${createdEntries.length}`);
        lines.push(`- Updated notes: ${updatedEntries.length}`);
        lines.push(`- Recreated notes: ${recreatedEntries.length}`);
        lines.push(`- Failed conversations: ${failedEntries.length}`);
        lines.push("");

        lines.push("## ✨ New Notes");
        lines.push("");
        if (createdEntries.length === 0) {
            lines.push("- None");
            lines.push("");
        } else {
            for (const entry of createdEntries) {
                const sanitizedTitle = entry.title.replace(/\n/g, " ").trim();
                const titleLink = `[[${entry.filePath}\\|${sanitizedTitle}]]`;
                lines.push(`- ✨ ${titleLink}`);
            }
            lines.push("");
        }

        lines.push("## 🔄 Updated Notes");
        lines.push("");
        if (updatedEntries.length === 0) {
            lines.push("- None");
            lines.push("");
        } else {
            for (const entry of updatedEntries) {
                const sanitizedTitle = entry.title.replace(/\n/g, " ").trim();
                const titleLink = `[[${entry.filePath}\\|${sanitizedTitle}]]`;
                lines.push(`- 🔄 ${titleLink}`);
            }
            lines.push("");
        }

        // Only when a rebuild happened: most imports never produce one, and an
        // empty section on a phone is a screenful of nothing.
        if (recreatedEntries.length > 0) {
            lines.push("## ♻️ Recreated Notes");
            lines.push("");
            for (const entry of recreatedEntries) {
                const sanitizedTitle = entry.title.replace(/\n/g, " ").trim();
                const titleLink = `[[${entry.filePath}\\|${sanitizedTitle}]]`;
                lines.push(`- ♻️ ${titleLink}`);
            }
            lines.push("");
        }

        if (failedEntries.length > 0) {
            const sortedFailures = [...failedEntries].sort((a, b) =>
                a.title.localeCompare(b.title, undefined, {
                    sensitivity: "base",
                })
            );
            lines.push("## Failed");
            lines.push("");
            for (const entry of sortedFailures) {
                const sanitizedTitle = entry.title.replace(/\n/g, " ").trim();
                lines.push(
                    `- ${sanitizedTitle} — ${
                        entry.errorMessage || "Unknown error"
                    }`
                );
            }
            lines.push("");
        }

        return lines.join("\n");
    }

    private getOrderedFileNames(allFiles?: File[]): string[] {
        if (!allFiles || allFiles.length === 0) {
            return Array.from(this.fileSections.keys());
        }

        const sortedFiles = [...allFiles].sort(
            (a, b) => a.lastModified - b.lastModified
        );
        const orderedNames: string[] = [];

        for (const file of sortedFiles) {
            if (this.fileSections.has(file.name)) {
                orderedNames.push(file.name);
            }
        }

        return orderedNames;
    }

    private generateFileContent(
        section: FileSection,
        isMultiFile: boolean
    ): string {
        let content = "";

        if (section.created.length > 0) {
            content += this.generateCreatedTable(section.created, isMultiFile);
        }

        if (section.updated.length > 0) {
            content += this.generateUpdatedTable(section.updated, isMultiFile);
        }

        if (section.recreated.length > 0) {
            content += this.generateRecreatedTable(
                section.recreated,
                isMultiFile
            );
        }

        if (section.failed.length > 0) {
            content += this.generateFailedTable(section.failed, isMultiFile);
        }

        return content;
    }

    private generateCreatedTable(
        entries: ReportEntry[],
        isMultiFile: boolean
    ): string {
        const header = isMultiFile
            ? "### ✨ Created Notes"
            : "## ✨ Created Notes";
        let table = `${header}\n\n`;
        table += `| | Title | Created | Messages | ${this.providerSpecificColumnHeader} |\n`;
        table += "|:---:|:---|:---:|:---:|:---:|\n";

        // Sort by createTime (oldest first, newest at bottom) - numeric sort
        const sortedEntries = [...entries].sort((a, b) => {
            return a.createTime - b.createTime;
        });

        sortedEntries.forEach((entry) => {
            const sanitizedTitle = entry.title.replace(/\n/g, " ").trim();
            const titleLink = `[[${entry.filePath}\\|${sanitizedTitle}]]`;
            const providerSpecificValue = entry.providerSpecificCount || 0;

            // Format timestamp with custom format or default
            const createDate = formatMessageTimestamp(
                entry.createTime,
                this.customTimestampFormat
            );

            // Add green checkmark for artifacts/attachments when > 0
            const providerSpecificDisplay =
                providerSpecificValue > 0
                    ? `✅ ${providerSpecificValue}`
                    : providerSpecificValue;

            table += `| ✨ | ${titleLink} | ${createDate} | ${
                entry.messageCount || 0
            } | ${providerSpecificDisplay} |\n`;
        });

        return table + "\n\n";
    }

    private generateRecreatedTable(
        entries: ReportEntry[],
        isMultiFile: boolean
    ): string {
        const header = isMultiFile
            ? "### ♻️ Recreated Notes"
            : "## ♻️ Recreated Notes";
        let table = `${header}\n\n`;
        // Whole-note counts, not "new" ones: a rebuild rewrites everything.
        table += `| | Title | Updated | Messages | ${this.providerSpecificColumnHeader} |\n`;
        table += "|:---:|:---|:---:|:---:|:---:|\n";

        const sortedEntries = [...entries].sort(
            (a, b) => a.updateTime - b.updateTime
        );

        sortedEntries.forEach((entry) => {
            const sanitizedTitle = entry.title.replace(/\n/g, " ").trim();
            const titleLink = `[[${entry.filePath}\\|${sanitizedTitle}]]`;
            const providerSpecificValue = entry.providerSpecificCount || 0;
            const updateDate = formatMessageTimestamp(
                entry.updateTime,
                this.customTimestampFormat
            );
            const providerSpecificDisplay =
                providerSpecificValue > 0
                    ? `✅ ${providerSpecificValue}`
                    : providerSpecificValue;

            table += `| ♻️ | ${titleLink} | ${updateDate} | ${
                entry.messageCount || 0
            } | ${providerSpecificDisplay} |\n`;
        });

        return table + "\n\n";
    }

    private generateUpdatedTable(
        entries: ReportEntry[],
        isMultiFile: boolean
    ): string {
        const header = isMultiFile
            ? "### 🔄 Updated Notes"
            : "## 🔄 Updated Notes";
        let table = `${header}\n\n`;
        table += `| | Title | Updated | New Messages | New ${this.providerSpecificColumnHeader} |\n`;
        table += "|:---:|:---|:---:|:---:|:---:|\n";

        // Sort by updateTime (oldest first, newest at bottom) - numeric sort
        const sortedEntries = [...entries].sort((a, b) => {
            return a.updateTime - b.updateTime;
        });

        sortedEntries.forEach((entry) => {
            const sanitizedTitle = entry.title.replace(/\n/g, " ").trim();
            const titleLink = `[[${entry.filePath}\\|${sanitizedTitle}]]`;
            const providerSpecificValue = entry.providerSpecificCount || 0;

            // Format timestamp with custom format or default
            const updateDate = formatMessageTimestamp(
                entry.updateTime,
                this.customTimestampFormat
            );

            // Add green checkmark for artifacts/attachments when > 0
            const providerSpecificDisplay =
                providerSpecificValue > 0
                    ? `✅ ${providerSpecificValue}`
                    : providerSpecificValue;

            table += `| 🔄 | ${titleLink} | ${updateDate} | ${
                entry.newMessageCount || 0
            } | ${providerSpecificDisplay} |\n`;
        });

        return table + "\n\n";
    }

    private generateFailedTable(
        entries: ReportEntry[],
        isMultiFile: boolean
    ): string {
        const header = isMultiFile
            ? "### 🚫 Failed Imports"
            : "## 🚫 Failed Imports";
        let table = `${header}\n\n`;
        table += "| | Title | Date | Error |\n";
        table += "|:---:|:---|:---:|:---|\n";

        // Sort by createTime (oldest first, newest at bottom) - numeric sort
        const sortedEntries = [...entries].sort((a, b) => {
            return a.createTime - b.createTime;
        });

        sortedEntries.forEach((entry) => {
            const sanitizedTitle = entry.title.replace(/\n/g, " ").trim();
            // Format timestamp with custom format or default
            const createDate = formatMessageTimestamp(
                entry.createTime,
                this.customTimestampFormat
            );
            table += `| 🚫 | ${sanitizedTitle} | ${createDate} | ${
                entry.errorMessage || "Unknown error"
            } |\n`;
        });

        return table + "\n\n";
    }

    private formatAttachmentStatus(stats?: AttachmentStats): string {
        if (!stats || stats.total === 0) {
            return "0";
        }

        const { total, found } = stats;

        if (found === total) {
            return `✅ ${found}`;
        } else if (found === 0) {
            return `❌ 0/${total}`;
        } else {
            return `⚠️ ${found}/${total}`;
        }
    }

    getCreatedCount(): number {
        let count = 0;
        this.fileSections.forEach((section) => {
            count += section.created.length;
        });
        return count;
    }

    getUpdatedCount(): number {
        let count = 0;
        this.fileSections.forEach((section) => {
            count += section.updated.length;
        });
        return count;
    }

    getRecreatedCount(): number {
        let count = 0;
        this.fileSections.forEach((section) => {
            count += section.recreated.length;
        });
        return count;
    }

    getIgnoredCount(): number {
        let count = 0;
        this.fileSections.forEach((section) => {
            count += section.ignored.length;
        });
        return count;
    }

    /**
     * Store file analysis stats for duplicate counting
     */
    setFileStats(fileStats: Map<string, FileAnalysisStats>) {
        this.fileStats = fileStats;
    }

    /**
     * Store analysis info for completion stats
     */
    setAnalysisInfo(analysisInfo: AnalysisInfo) {
        this.analysisInfo = analysisInfo;
    }

    /**
     * Record what the selection dialog offered and what the user kept. Without
     * it the conversations the user declined are counted nowhere: they are not
     * unchanged, not failed, and never reach the processor.
     */
    setSelection(offered: number, selected: number) {
        this.selection = { offered, selected };
    }

    setIgnoredArchives(ignoredArchives: IgnoredArchiveDetail[]) {
        this.ignoredArchiveDetails.clear();
        ignoredArchives.forEach((archive) => {
            this.ignoredArchiveDetails.set(archive.fileName, archive);
        });
    }

    /**
     * Calculate total duplicates from file stats
     */
    private getTotalDuplicates(): number {
        if (!this.fileStats) return 0;

        let totalDuplicates = 0;
        this.fileStats.forEach((stats) => {
            totalDuplicates += stats.duplicates || 0;
        });
        return totalDuplicates;
    }

    /**
     * Every conversation number the plugin reports, resolved once.
     *
     * Two phases produce these counts. The archive analysis knows what the ZIPs
     * held and what it decided to do; the vault writes know what actually
     * landed. The mobile flow (handleImportAllMobileSequential) skips the
     * analysis entirely, so `analysisAvailable` is false there and the write
     * counters are the only truth — which is why the fallbacks below exist
     * rather than being a smell to remove. They live here, once, instead of
     * being re-decided at each render.
     */
    getConversationLedger(): ConversationLedger {
        const writes = this.getGlobalStats();
        const analysis = this.analysisInfo;

        return {
            analysisAvailable: analysis !== undefined,

            // Archive-side. Zero without an analysis phase; read them only
            // behind `analysisAvailable` so they never render as a real zero.
            totalFound: analysis?.totalConversationsFound ?? 0,
            uniqueKept: analysis?.uniqueConversationsKept ?? 0,
            unchanged: analysis?.conversationsUnchanged ?? 0,
            reprocessed: analysis?.conversationsReprocessed ?? 0,

            // Vault-side.
            created: writes.created,
            updated: writes.updated,
            recreated: writes.recreated,
            failed: writes.failed,
            empty: this.getIgnoredCount(),
            noChange: writes.skipped,

            // Resolved. On the mobile flow an unchanged conversation reaches
            // the processor and is recorded by addSkipped, so the write
            // counter carries the same meaning the analysis would have.
            selected:
                this.selection?.selected ??
                analysis?.uniqueConversationsKept ??
                writes.totalProcessed,
            notSelected: this.selection
                ? Math.max(0, this.selection.offered - this.selection.selected)
                : null,
            // A sum, not a choice: the two counters hold disjoint populations.
            // The analysis one counts conversations dropped before the import
            // ever saw them (a full import without a rebuild); the write one
            // counts those that reached the processor and produced nothing
            // (a selective import, where every existing conversation is
            // offered). Picking one made a selected-but-unchanged conversation
            // vanish from the report and broke its arithmetic.
            unchangedSkipped:
                (analysis?.conversationsDroppedUnchanged ?? 0) + writes.skipped,
            totalConversations:
                analysis?.uniqueConversationsKept ?? writes.totalProcessed,
            duplicates:
                analysis?.duplicatesRemoved ?? this.getTotalDuplicates(),
        };
    }

    /**
     * Get statistics for the completion dialog
     */
    getCompletionStats() {
        const ledger = this.getConversationLedger();
        const attachmentStats = this.getTotalAttachmentStats();

        return {
            totalFiles: this.fileSections.size,
            totalConversations: ledger.totalConversations,
            duplicates: ledger.duplicates,
            created: ledger.created,
            updated: ledger.updated,
            recreated: ledger.recreated,
            unchanged: ledger.unchangedSkipped,
            notSelected: ledger.notSelected,
            emptyConversations: ledger.empty,
            failed: ledger.failed,
            attachmentsFound: attachmentStats.found,
            attachmentsTotal: attachmentStats.total,
            attachmentsMissing: attachmentStats.missing,
            attachmentsFailed: attachmentStats.failed,
        };
    }

    /**
     * Get list of processed file names
     */
    getProcessedFileNames(): string[] {
        return Array.from(this.fileSections.keys());
    }

    private buildArchiveReason(
        fileName: string,
        status: "processed" | "not processed",
        isSelectiveImport?: boolean
    ): string {
        if (status === "processed") {
            return "imported";
        }

        const ignored = this.ignoredArchiveDetails.get(fileName);
        if (ignored) {
            return `${this.formatIgnoredArchiveReason(ignored.reason)}: ${
                ignored.message
            }`;
        }

        // "Nothing was imported from this archive" covers three situations a
        // reader reacts to differently: an archive with nothing exploitable,
        // one whose every conversation arrived in a newer archive, and one
        // the vault is already ahead of. The per-file stats tell them apart.
        const stats = this.fileStats?.get(fileName);

        if (stats && stats.totalConversations === 0) {
            return "no importable conversations";
        }

        if (stats && stats.uniqueContributed === 0) {
            return "superseded by another archive";
        }

        if (isSelectiveImport) {
            return "no selected conversations";
        }

        return stats ? "already up to date" : "no importable conversations";
    }

    private formatIgnoredArchiveReason(reason: string): string {
        switch (reason) {
            case "provider-mismatch":
                return "provider mismatch";
            case "unsupported-format":
                return "unsupported format";
            case "nested-zip-container":
                return "nested ZIP container";
            case "empty":
                return "empty archive";
            case "read-error":
                return "read error";
            default:
                return reason;
        }
    }
}
